server:
  port: 8093

# database 연동 설정
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 각자꺼 부분 드레그해서 주석 처리하는거랑 똑같이 ctrl+/ 해서 주석 풀고 사용하면 돼요
    # 윤서꺼?
    # url: jdbc:mysql://localhost:3306/toy?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    # username: root
    # password: ys123456
#=======
#    url: jdbc:mysql://concat-1.clc60kwem0qc.ap-northeast-2.rds.amazonaws.com:3306/concat_toyDB?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
#    username: root
#    password: concat0901^^aw
#
#=======
#윤서꺼?
#     url: jdbc:mysql://localhost:3306/toy?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
#     username: root
#     password: ys123456
#    url: jdbc:mysql://localhost:3306/toyProjectBoard?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
#    username: root
#    password: root
# 혜은이꺼?
#     url: "jdbc:mysql://localhost:3306/db_coding?serverTimezone=Asia/Seoul&characterEncoding=UTF-8"
#     username: user_coding
#     password: coding!^^!
#
    # 서윤꺼
    # url: jdbc:mysql://localhost:3306/toyProjectBoard?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    # username: root
    # password: root
  thymeleaf:
    cache: false

  # spring data jpa 설정
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update
